version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./.docker/entrypoint.sh
    env_file:
      - .env      
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
